# Generated by Django 4.2.5 on 2023-09-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_movie_pg_movie_posteruri_movie_synopsis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('birthdate', models.DateField(null=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
    ]
