# Generated by Django 4.2.5 on 2023-09-29 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_movie_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='directedMovies', to='movieapp.person'),
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=150, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movieapp.person')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movieapp.movie')),
            ],
            options={
                'db_table': 'play',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(related_name='playedMovies', through='movieapp.Play', to='movieapp.person'),
        ),
    ]
